version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: martina
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: phishing_awareness
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tesis_network

  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: phishing_awareness
      DB_POSTGRESDB_USER: martina
      DB_POSTGRESDB_PASSWORD: 1234
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: martina
      N8N_BASIC_AUTH_PASSWORD: 1234
    depends_on:
      - postgres
    networks:
      - tesis_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: martinamolina987@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - tesis_network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate --url http://host.docker.internal:5678
    depends_on:
      - n8n
    networks:
      - tesis_network

volumes:
  postgres_data:

networks:
  tesis_network:
    driver: bridge